img_size: 512
class_num: 21
img_mean: [123, 117, 104]
root: "Object_detection_2d/SSD"

prior:
  feature_map_sizes: [64, 32, 16, 8, 4, 2, 1]
  min_sizes: [35.84, 76.8, 153.6, 230.4, 307.2, 384.0, 460.8]
  max_sizes: [76.8, 153.6, 230.4, 307.2, 384.0, 460.8, 537.65]
  strides: [8, 16, 32, 64, 128, 256, 512]
  aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
  boxes_per_feature_map: [4, 6, 6, 6, 6, 4, 4]
  clip: True

target_transform: Coord
center_variance: 0.1
size_variance: 0.2
iou_thres: 0.5

model: "SSD"
backbone:
  model: 'vgg'
  out_channels: [512, 1024, 512, 256, 256, 256, 256]
  pretrained: True

datasets:
  name: "VOC"
  data_root: Dataset/VOC
  train:
    years: ["2007", "2012"]
    splits: ["trainval", "trainval"]
    download_data: [False, False]
  eval:
    years: ["2012"]
    splits: ["val"]
    download_data: [False]
  test:
    years: ["2012"]
    splits: ["val"]
    download_data: [False]

# Training
epochs: 200
scheduler:
  name: "WarmupMultiStep"
  milestones: [80000, 100000]
  gamma: 0.1
  warmup_factor: 0.333
  warmup_iters: 500
  last_epoch: -1

optimizer:
  name: "SGD"
  weight_decay: 0.0005
  momentum: 0.9
  lr: 0.001

loss:
  name: MultiBoxesIouLoss
  neg_pos_ratio: 3
  box_loss_weight: 1.0
  center_variance: 0.1
  size_variance: 0.2

train_batch_size: 32
eval_batch_size: 32
test_batch_size: 4

# Evaluation
confidence_thres: 0.01
nms_thres: 0.45
topk: 100

# Test
score_thres: 0.7