class_num: &class_num 21
ignore_index: &ignore_index 255
root: "Segmentation_2d"
task: &task "img_seg"
img_size: &img_size 512

img_mean: &img_mean [0.485, 0.456, 0.406]
img_std: &img_std [0.229, 0.224, 0.225]
dataset_name: &dataset_name "VOC"

year: "2012"
download: False
data_path: Dataset/VOC
train_batch_size: 8
val_batch_size: 4
test_batch_size: 4

transforms:
  train:
    - type: ResizeShorterSide
      shorter_size: *img_size
    - type: RandomCrop
      crop_size: *img_size
      ignore_index: *ignore_index
      pad_if_needed: True
    - type: RandomHorizontalFlip
    - type: ToTensor
    - type: Normalize
      mean: *img_mean
      std: *img_std
  val:
    - type: ResizeLetterBoxes
      size: *img_size
      ignore_index: *ignore_index
    - type: ToTensor
    - type: Normalize
      mean: *img_mean
      std: *img_std
  test:
    - type: ResizeLetterBoxes
      size: *img_size
      ignore_index: *ignore_index
    - type: ToTensor
    - type: Normalize
      mean: *img_mean
      std: *img_std

model:
  name: "SegFormer"
  in_channels: 3
  embed_dims: [64, 128, 320, 512]
  n_heads: [1, 2, 5, 8]
  mlp_ratios: [4, 4, 4, 4]
  patch_sizes: [7, 3, 3, 3]
  strides: [4, 2, 2, 2]
  depths: [3, 4, 6, 3]
  reduction_ratios: [8, 4, 2, 1]
  qkv_bias: True
  drop_path_rate: 0.1
  head_embed_dim: 256
  class_num: *class_num
  weight_init: "attention"
  pretrained_weights: "Segmentation_2d/pretrained_weights/SegFormer2/mit_b2_backbone.pth"

# Training
epochs: 200
scheduler:
  name: "Poly"
  max_iters: 90000

optimizer:
  name: "AdamW"
  weight_decay: 0.01
  lr: 0.0001

loss:
  name: CrossEntropyLoss
  ignore_index: *ignore_index
  # lovasz_weight: 1.5
  # boundary_weight: 0.5

metrics:
  name: "ConfusionMatrix"
  task: *task
  class_num: *class_num
  ignore_index: *ignore_index

visualizer:
  name: "ImageSegVisualizer"
  dataset_name: *dataset_name
  mean: *img_mean
  std: *img_std