apiVersion: batch/v1
kind: Job
metadata:
  name: tungyen-akb48-download # replace with "${USER_NAME}-{JOB_NAME}"
  namespace: ucsd-haosulab
spec:
  ttlSecondsAfterFinished: 86400 # Wait one day to delete completed jobs
  template:
    spec:
      containers:
        - name: gpu-container
          image: pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime # docker image
          # imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
          args:
            - "cd /yen-fast-vol/ && pip install pandas && apt-get update && apt-get install unzip && cd ARKitScenes/ && python3 download_data.py 3dod --video_id_csv threedod/3dod_train_val_splits.csv --download_dir threedod/"
            # For multiple commands, concatenate them with &&
          resources:
            requests:
              cpu: "3"
              memory: "8Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "4"
              memory: "16Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: yen-fast-vol
              mountPath: /yen-fast-vol
      volumes:
        - name: dshm # shared memory, required for the multi-worker dataloader
          emptyDir:
            medium: Memory
        - name: yen-fast-vol
          persistentVolumeClaim:
            claimName: yen-fast-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nautilus.io/group
                    operator: In
                    values:
                      - haosu
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-2080-Ti
  backoffLimit: 0 # The number of attempts to restart after crash
