apiVersion: v1
kind: Pod
metadata:
  name: tungyen-test
  namespace: ucsd-haosulab
  annotations:
    yunikorn.apache.org/allow-preemption: "true"
spec:
  tolerations:
    - key: "nautilus.io/nrp-testing"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: gpu-container
      image: tungyenchiang/resample-image
      # imagePullPolicy: Always
      args: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "4"
          memory: "32Gi"
          nvidia.com/gpu: "1"
          ephemeral-storage: "30Gi"
        limits:
          cpu: "4"
          memory: "32Gi"
          nvidia.com/gpu: "1"
          ephemeral-storage: "30Gi"
      volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: tungyen-fast-vol
          mountPath: /tungyen-fast-vol
  volumes:
    - name: dshm # shared memory, required for the multi-worker dataloader
      emptyDir:
        medium: Memory
    - name: tungyen-fast-vol
      persistentVolumeClaim:
        claimName: tungyen-fast-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              # - key: nautilus.io/group
              #   operator: In
              #   values:
              #     - k8s-4090-01.calit2.optiputer.net
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
